// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 消息ID
type MessageID int32

const (
	MessageID_MSG_Ping                   MessageID = 0
	MessageID_MSG_Pong                   MessageID = 1
	MessageID_MSG_Error_S2C              MessageID = 2
	MessageID_MSG_Login_C2S              MessageID = 3
	MessageID_MSG_Login_S2C              MessageID = 4
	MessageID_MSG_Logout_C2S             MessageID = 5
	MessageID_MSG_Logout_S2C             MessageID = 6
	MessageID_MSG_QuickStart_C2S         MessageID = 7
	MessageID_MSG_ChangeTable_C2S        MessageID = 8
	MessageID_MSG_JoinRoom_S2C           MessageID = 9
	MessageID_MSG_EnterRoom_S2C          MessageID = 10
	MessageID_MSG_NoticeJoin_S2C         MessageID = 11
	MessageID_MSG_LeaveRoom_C2S          MessageID = 12
	MessageID_MSG_LeaveRoom_S2C          MessageID = 13
	MessageID_MSG_SitDown_C2S            MessageID = 14
	MessageID_MSG_SitDown_S2C            MessageID = 15
	MessageID_MSG_StandUp_C2S            MessageID = 16
	MessageID_MSG_StandUp_S2C            MessageID = 17
	MessageID_MSG_PlayerAction_C2S       MessageID = 18
	MessageID_MSG_PlayerAction_S2C       MessageID = 19
	MessageID_MSG_PlayerActionChange_S2C MessageID = 20
	MessageID_MSG_AddChips_C2S           MessageID = 21
	MessageID_MSG_AddChips_S2C           MessageID = 22
	MessageID_MSG_GameStepChange_S2C     MessageID = 23
	MessageID_MSG_ResultGameData_S2C     MessageID = 24
	MessageID_MSG_ReadyTime_S2C          MessageID = 25
	MessageID_MSG_SettleTime_S2C         MessageID = 26
	MessageID_MSG_PushCardTime_S2C       MessageID = 27
	MessageID_MSG_RoomStatus_C2S         MessageID = 28
	MessageID_MSG_RoomStatus_S2C         MessageID = 29
	MessageID_MSG_EmojiChat_C2S          MessageID = 30
	MessageID_MSG_EmojiChat_S2C          MessageID = 31
	MessageID_MSG_PiPeiPlayer_S2C        MessageID = 32
)

var MessageID_name = map[int32]string{
	0:  "MSG_Ping",
	1:  "MSG_Pong",
	2:  "MSG_Error_S2C",
	3:  "MSG_Login_C2S",
	4:  "MSG_Login_S2C",
	5:  "MSG_Logout_C2S",
	6:  "MSG_Logout_S2C",
	7:  "MSG_QuickStart_C2S",
	8:  "MSG_ChangeTable_C2S",
	9:  "MSG_JoinRoom_S2C",
	10: "MSG_EnterRoom_S2C",
	11: "MSG_NoticeJoin_S2C",
	12: "MSG_LeaveRoom_C2S",
	13: "MSG_LeaveRoom_S2C",
	14: "MSG_SitDown_C2S",
	15: "MSG_SitDown_S2C",
	16: "MSG_StandUp_C2S",
	17: "MSG_StandUp_S2C",
	18: "MSG_PlayerAction_C2S",
	19: "MSG_PlayerAction_S2C",
	20: "MSG_PlayerActionChange_S2C",
	21: "MSG_AddChips_C2S",
	22: "MSG_AddChips_S2C",
	23: "MSG_GameStepChange_S2C",
	24: "MSG_ResultGameData_S2C",
	25: "MSG_ReadyTime_S2C",
	26: "MSG_SettleTime_S2C",
	27: "MSG_PushCardTime_S2C",
	28: "MSG_RoomStatus_C2S",
	29: "MSG_RoomStatus_S2C",
	30: "MSG_EmojiChat_C2S",
	31: "MSG_EmojiChat_S2C",
	32: "MSG_PiPeiPlayer_S2C",
}

var MessageID_value = map[string]int32{
	"MSG_Ping":                   0,
	"MSG_Pong":                   1,
	"MSG_Error_S2C":              2,
	"MSG_Login_C2S":              3,
	"MSG_Login_S2C":              4,
	"MSG_Logout_C2S":             5,
	"MSG_Logout_S2C":             6,
	"MSG_QuickStart_C2S":         7,
	"MSG_ChangeTable_C2S":        8,
	"MSG_JoinRoom_S2C":           9,
	"MSG_EnterRoom_S2C":          10,
	"MSG_NoticeJoin_S2C":         11,
	"MSG_LeaveRoom_C2S":          12,
	"MSG_LeaveRoom_S2C":          13,
	"MSG_SitDown_C2S":            14,
	"MSG_SitDown_S2C":            15,
	"MSG_StandUp_C2S":            16,
	"MSG_StandUp_S2C":            17,
	"MSG_PlayerAction_C2S":       18,
	"MSG_PlayerAction_S2C":       19,
	"MSG_PlayerActionChange_S2C": 20,
	"MSG_AddChips_C2S":           21,
	"MSG_AddChips_S2C":           22,
	"MSG_GameStepChange_S2C":     23,
	"MSG_ResultGameData_S2C":     24,
	"MSG_ReadyTime_S2C":          25,
	"MSG_SettleTime_S2C":         26,
	"MSG_PushCardTime_S2C":       27,
	"MSG_RoomStatus_C2S":         28,
	"MSG_RoomStatus_S2C":         29,
	"MSG_EmojiChat_C2S":          30,
	"MSG_EmojiChat_S2C":          31,
	"MSG_PiPeiPlayer_S2C":        32,
}

func (x MessageID) String() string {
	return proto.EnumName(MessageID_name, int32(x))
}

func (MessageID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

type ErrorMsg int32

const (
	ErrorMsg_SUCCESS               ErrorMsg = 0
	ErrorMsg_UserRepeatLogin       ErrorMsg = 101
	ErrorMsg_UserRemoteLogin       ErrorMsg = 102
	ErrorMsg_ChipsInsufficient     ErrorMsg = 103
	ErrorMsg_ChairAlreadyFull      ErrorMsg = 104
	ErrorMsg_UserNotChangeTable    ErrorMsg = 105
	ErrorMsg_UserTimeOutFoldCard   ErrorMsg = 106
	ErrorMsg_UserStandUpTimeOut    ErrorMsg = 107
	ErrorMsg_UserInGameNotStandUp  ErrorMsg = 108
	ErrorMsg_UserInGameStandUpFold ErrorMsg = 109
)

var ErrorMsg_name = map[int32]string{
	0:   "SUCCESS",
	101: "UserRepeatLogin",
	102: "UserRemoteLogin",
	103: "ChipsInsufficient",
	104: "ChairAlreadyFull",
	105: "UserNotChangeTable",
	106: "UserTimeOutFoldCard",
	107: "UserStandUpTimeOut",
	108: "UserInGameNotStandUp",
	109: "UserInGameStandUpFold",
}

var ErrorMsg_value = map[string]int32{
	"SUCCESS":               0,
	"UserRepeatLogin":       101,
	"UserRemoteLogin":       102,
	"ChipsInsufficient":     103,
	"ChairAlreadyFull":      104,
	"UserNotChangeTable":    105,
	"UserTimeOutFoldCard":   106,
	"UserStandUpTimeOut":    107,
	"UserInGameNotStandUp":  108,
	"UserInGameStandUpFold": 109,
}

func (x ErrorMsg) String() string {
	return proto.EnumName(ErrorMsg_name, int32(x))
}

func (ErrorMsg) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

// 牌型
type CardSuit int32

const (
	CardSuit_XXX_Card      CardSuit = 0
	CardSuit_HighCard      CardSuit = 1
	CardSuit_OnePair       CardSuit = 2
	CardSuit_TwoPairs      CardSuit = 3
	CardSuit_ThreeKind     CardSuit = 4
	CardSuit_Straight      CardSuit = 5
	CardSuit_Flush         CardSuit = 6
	CardSuit_FullHouse     CardSuit = 7
	CardSuit_FourKind      CardSuit = 8
	CardSuit_StraightFlush CardSuit = 9
	CardSuit_RoyalFlush    CardSuit = 10
)

var CardSuit_name = map[int32]string{
	0:  "XXX_Card",
	1:  "HighCard",
	2:  "OnePair",
	3:  "TwoPairs",
	4:  "ThreeKind",
	5:  "Straight",
	6:  "Flush",
	7:  "FullHouse",
	8:  "FourKind",
	9:  "StraightFlush",
	10: "RoyalFlush",
}

var CardSuit_value = map[string]int32{
	"XXX_Card":      0,
	"HighCard":      1,
	"OnePair":       2,
	"TwoPairs":      3,
	"ThreeKind":     4,
	"Straight":      5,
	"Flush":         6,
	"FullHouse":     7,
	"FourKind":      8,
	"StraightFlush": 9,
	"RoyalFlush":    10,
}

func (x CardSuit) String() string {
	return proto.EnumName(CardSuit_name, int32(x))
}

func (CardSuit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

// 游戏阶段
type GameStep int32

const (
	GameStep_Waiting  GameStep = 0
	GameStep_PreFlop  GameStep = 1
	GameStep_Flop     GameStep = 2
	GameStep_Turn     GameStep = 3
	GameStep_River    GameStep = 4
	GameStep_ShowDown GameStep = 5
)

var GameStep_name = map[int32]string{
	0: "Waiting",
	1: "PreFlop",
	2: "Flop",
	3: "Turn",
	4: "River",
	5: "ShowDown",
}

var GameStep_value = map[string]int32{
	"Waiting":  0,
	"PreFlop":  1,
	"Flop":     2,
	"Turn":     3,
	"River":    4,
	"ShowDown": 5,
}

func (x GameStep) String() string {
	return proto.EnumName(GameStep_name, int32(x))
}

func (GameStep) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

// 玩家操作状态
type ActionStatus int32

const (
	ActionStatus_WAITING ActionStatus = 0
	ActionStatus_RAISE   ActionStatus = 1
	ActionStatus_CALL    ActionStatus = 2
	ActionStatus_CHECK   ActionStatus = 3
	ActionStatus_FOLD    ActionStatus = 4
	ActionStatus_ALLIN   ActionStatus = 5
)

var ActionStatus_name = map[int32]string{
	0: "WAITING",
	1: "RAISE",
	2: "CALL",
	3: "CHECK",
	4: "FOLD",
	5: "ALLIN",
}

var ActionStatus_value = map[string]int32{
	"WAITING": 0,
	"RAISE":   1,
	"CALL":    2,
	"CHECK":   3,
	"FOLD":    4,
	"ALLIN":   5,
}

func (x ActionStatus) String() string {
	return proto.EnumName(ActionStatus_name, int32(x))
}

func (ActionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

// 盲注类型
type BlindType int32

const (
	BlindType_No_Blind    BlindType = 0
	BlindType_Small_Blind BlindType = 1
	BlindType_Big_Blind   BlindType = 2
)

var BlindType_name = map[int32]string{
	0: "No_Blind",
	1: "Small_Blind",
	2: "Big_Blind",
}

var BlindType_value = map[string]int32{
	"No_Blind":    0,
	"Small_Blind": 1,
	"Big_Blind":   2,
}

func (x BlindType) String() string {
	return proto.EnumName(BlindType_name, int32(x))
}

func (BlindType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type Pong struct {
	ServerTime           int64    `protobuf:"varint,1,opt,name=serverTime,proto3" json:"serverTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetServerTime() int64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

type Error_S2C struct {
	Error                ErrorMsg `protobuf:"varint,1,opt,name=error,proto3,enum=msg.ErrorMsg" json:"error,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error_S2C) Reset()         { *m = Error_S2C{} }
func (m *Error_S2C) String() string { return proto.CompactTextString(m) }
func (*Error_S2C) ProtoMessage()    {}
func (*Error_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *Error_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error_S2C.Unmarshal(m, b)
}
func (m *Error_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error_S2C.Marshal(b, m, deterministic)
}
func (m *Error_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error_S2C.Merge(m, src)
}
func (m *Error_S2C) XXX_Size() int {
	return xxx_messageInfo_Error_S2C.Size(m)
}
func (m *Error_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_Error_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_Error_S2C proto.InternalMessageInfo

func (m *Error_S2C) GetError() ErrorMsg {
	if m != nil {
		return m.Error
	}
	return ErrorMsg_SUCCESS
}

func (m *Error_S2C) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Login_C2S struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PassWord             string   `protobuf:"bytes,2,opt,name=PassWord,proto3" json:"PassWord,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_C2S) Reset()         { *m = Login_C2S{} }
func (m *Login_C2S) String() string { return proto.CompactTextString(m) }
func (*Login_C2S) ProtoMessage()    {}
func (*Login_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *Login_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_C2S.Unmarshal(m, b)
}
func (m *Login_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_C2S.Marshal(b, m, deterministic)
}
func (m *Login_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_C2S.Merge(m, src)
}
func (m *Login_C2S) XXX_Size() int {
	return xxx_messageInfo_Login_C2S.Size(m)
}
func (m *Login_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_Login_C2S proto.InternalMessageInfo

func (m *Login_C2S) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Login_C2S) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *Login_C2S) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type PlayerInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	NickName             string   `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	HeadImg              string   `protobuf:"bytes,3,opt,name=headImg,proto3" json:"headImg,omitempty"`
	Account              float64  `protobuf:"fixed64,4,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlayerInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *PlayerInfo) GetHeadImg() string {
	if m != nil {
		return m.HeadImg
	}
	return ""
}

func (m *PlayerInfo) GetAccount() float64 {
	if m != nil {
		return m.Account
	}
	return 0
}

type Login_S2C struct {
	PlayerInfo           *PlayerInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Login_S2C) Reset()         { *m = Login_S2C{} }
func (m *Login_S2C) String() string { return proto.CompactTextString(m) }
func (*Login_S2C) ProtoMessage()    {}
func (*Login_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *Login_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_S2C.Unmarshal(m, b)
}
func (m *Login_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_S2C.Marshal(b, m, deterministic)
}
func (m *Login_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_S2C.Merge(m, src)
}
func (m *Login_S2C) XXX_Size() int {
	return xxx_messageInfo_Login_S2C.Size(m)
}
func (m *Login_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_Login_S2C proto.InternalMessageInfo

func (m *Login_S2C) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type Logout_C2S struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Logout_C2S) Reset()         { *m = Logout_C2S{} }
func (m *Logout_C2S) String() string { return proto.CompactTextString(m) }
func (*Logout_C2S) ProtoMessage()    {}
func (*Logout_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{6}
}

func (m *Logout_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Logout_C2S.Unmarshal(m, b)
}
func (m *Logout_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Logout_C2S.Marshal(b, m, deterministic)
}
func (m *Logout_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Logout_C2S.Merge(m, src)
}
func (m *Logout_C2S) XXX_Size() int {
	return xxx_messageInfo_Logout_C2S.Size(m)
}
func (m *Logout_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_Logout_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_Logout_C2S proto.InternalMessageInfo

type Logout_S2C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Logout_S2C) Reset()         { *m = Logout_S2C{} }
func (m *Logout_S2C) String() string { return proto.CompactTextString(m) }
func (*Logout_S2C) ProtoMessage()    {}
func (*Logout_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{7}
}

func (m *Logout_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Logout_S2C.Unmarshal(m, b)
}
func (m *Logout_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Logout_S2C.Marshal(b, m, deterministic)
}
func (m *Logout_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Logout_S2C.Merge(m, src)
}
func (m *Logout_S2C) XXX_Size() int {
	return xxx_messageInfo_Logout_S2C.Size(m)
}
func (m *Logout_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_Logout_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_Logout_S2C proto.InternalMessageInfo

// 牌型数据
type CardSuitData struct {
	HandCardKeys         []int32  `protobuf:"varint,1,rep,packed,name=handCardKeys,proto3" json:"handCardKeys,omitempty"`
	PublicCardKeys       []int32  `protobuf:"varint,2,rep,packed,name=publicCardKeys,proto3" json:"publicCardKeys,omitempty"`
	SuitPattern          CardSuit `protobuf:"varint,3,opt,name=suitPattern,proto3,enum=msg.CardSuit" json:"suitPattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardSuitData) Reset()         { *m = CardSuitData{} }
func (m *CardSuitData) String() string { return proto.CompactTextString(m) }
func (*CardSuitData) ProtoMessage()    {}
func (*CardSuitData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{8}
}

func (m *CardSuitData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardSuitData.Unmarshal(m, b)
}
func (m *CardSuitData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardSuitData.Marshal(b, m, deterministic)
}
func (m *CardSuitData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardSuitData.Merge(m, src)
}
func (m *CardSuitData) XXX_Size() int {
	return xxx_messageInfo_CardSuitData.Size(m)
}
func (m *CardSuitData) XXX_DiscardUnknown() {
	xxx_messageInfo_CardSuitData.DiscardUnknown(m)
}

var xxx_messageInfo_CardSuitData proto.InternalMessageInfo

func (m *CardSuitData) GetHandCardKeys() []int32 {
	if m != nil {
		return m.HandCardKeys
	}
	return nil
}

func (m *CardSuitData) GetPublicCardKeys() []int32 {
	if m != nil {
		return m.PublicCardKeys
	}
	return nil
}

func (m *CardSuitData) GetSuitPattern() CardSuit {
	if m != nil {
		return m.SuitPattern
	}
	return CardSuit_XXX_Card
}

type PlayerData struct {
	PlayerInfo           *PlayerInfo   `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	Chair                int32         `protobuf:"varint,2,opt,name=chair,proto3" json:"chair,omitempty"`
	StandUPNum           int32         `protobuf:"varint,3,opt,name=standUPNum,proto3" json:"standUPNum,omitempty"`
	Chips                float64       `protobuf:"fixed64,4,opt,name=chips,proto3" json:"chips,omitempty"`
	RoomChips            float64       `protobuf:"fixed64,5,opt,name=roomChips,proto3" json:"roomChips,omitempty"`
	ActionStatus         ActionStatus  `protobuf:"varint,6,opt,name=actionStatus,proto3,enum=msg.ActionStatus" json:"actionStatus,omitempty"`
	GameStep             int32         `protobuf:"varint,7,opt,name=gameStep,proto3" json:"gameStep,omitempty"`
	DownBets             float64       `protobuf:"fixed64,8,opt,name=downBets,proto3" json:"downBets,omitempty"`
	LunDownBets          float64       `protobuf:"fixed64,9,opt,name=lunDownBets,proto3" json:"lunDownBets,omitempty"`
	TotalDownBet         float64       `protobuf:"fixed64,10,opt,name=totalDownBet,proto3" json:"totalDownBet,omitempty"`
	HandCards            []int32       `protobuf:"varint,11,rep,packed,name=handCards,proto3" json:"handCards,omitempty"`
	CardSuitData         *CardSuitData `protobuf:"bytes,12,opt,name=cardSuitData,proto3" json:"cardSuitData,omitempty"`
	ResultMoney          float64       `protobuf:"fixed64,13,opt,name=resultMoney,proto3" json:"resultMoney,omitempty"`
	BlindType            BlindType     `protobuf:"varint,14,opt,name=blindType,proto3,enum=msg.BlindType" json:"blindType,omitempty"`
	IsButton             bool          `protobuf:"varint,15,opt,name=IsButton,proto3" json:"IsButton,omitempty"`
	IsAllIn              bool          `protobuf:"varint,16,opt,name=IsAllIn,proto3" json:"IsAllIn,omitempty"`
	IsWinner             bool          `protobuf:"varint,17,opt,name=IsWinner,proto3" json:"IsWinner,omitempty"`
	IsInGame             bool          `protobuf:"varint,18,opt,name=IsInGame,proto3" json:"IsInGame,omitempty"`
	IsStandUp            bool          `protobuf:"varint,19,opt,name=IsStandUp,proto3" json:"IsStandUp,omitempty"`
	TimerCount           int32         `protobuf:"varint,20,opt,name=timerCount,proto3" json:"timerCount,omitempty"`
	Account              float64       `protobuf:"fixed64,21,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PlayerData) Reset()         { *m = PlayerData{} }
func (m *PlayerData) String() string { return proto.CompactTextString(m) }
func (*PlayerData) ProtoMessage()    {}
func (*PlayerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{9}
}

func (m *PlayerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerData.Unmarshal(m, b)
}
func (m *PlayerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerData.Marshal(b, m, deterministic)
}
func (m *PlayerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerData.Merge(m, src)
}
func (m *PlayerData) XXX_Size() int {
	return xxx_messageInfo_PlayerData.Size(m)
}
func (m *PlayerData) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerData.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerData proto.InternalMessageInfo

func (m *PlayerData) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *PlayerData) GetChair() int32 {
	if m != nil {
		return m.Chair
	}
	return 0
}

func (m *PlayerData) GetStandUPNum() int32 {
	if m != nil {
		return m.StandUPNum
	}
	return 0
}

func (m *PlayerData) GetChips() float64 {
	if m != nil {
		return m.Chips
	}
	return 0
}

func (m *PlayerData) GetRoomChips() float64 {
	if m != nil {
		return m.RoomChips
	}
	return 0
}

func (m *PlayerData) GetActionStatus() ActionStatus {
	if m != nil {
		return m.ActionStatus
	}
	return ActionStatus_WAITING
}

func (m *PlayerData) GetGameStep() int32 {
	if m != nil {
		return m.GameStep
	}
	return 0
}

func (m *PlayerData) GetDownBets() float64 {
	if m != nil {
		return m.DownBets
	}
	return 0
}

func (m *PlayerData) GetLunDownBets() float64 {
	if m != nil {
		return m.LunDownBets
	}
	return 0
}

func (m *PlayerData) GetTotalDownBet() float64 {
	if m != nil {
		return m.TotalDownBet
	}
	return 0
}

func (m *PlayerData) GetHandCards() []int32 {
	if m != nil {
		return m.HandCards
	}
	return nil
}

func (m *PlayerData) GetCardSuitData() *CardSuitData {
	if m != nil {
		return m.CardSuitData
	}
	return nil
}

func (m *PlayerData) GetResultMoney() float64 {
	if m != nil {
		return m.ResultMoney
	}
	return 0
}

func (m *PlayerData) GetBlindType() BlindType {
	if m != nil {
		return m.BlindType
	}
	return BlindType_No_Blind
}

func (m *PlayerData) GetIsButton() bool {
	if m != nil {
		return m.IsButton
	}
	return false
}

func (m *PlayerData) GetIsAllIn() bool {
	if m != nil {
		return m.IsAllIn
	}
	return false
}

func (m *PlayerData) GetIsWinner() bool {
	if m != nil {
		return m.IsWinner
	}
	return false
}

func (m *PlayerData) GetIsInGame() bool {
	if m != nil {
		return m.IsInGame
	}
	return false
}

func (m *PlayerData) GetIsStandUp() bool {
	if m != nil {
		return m.IsStandUp
	}
	return false
}

func (m *PlayerData) GetTimerCount() int32 {
	if m != nil {
		return m.TimerCount
	}
	return 0
}

func (m *PlayerData) GetAccount() float64 {
	if m != nil {
		return m.Account
	}
	return 0
}

type RoomData struct {
	RoomId               string        `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	CfgId                string        `protobuf:"bytes,2,opt,name=cfgId,proto3" json:"cfgId,omitempty"`
	GameStep             GameStep      `protobuf:"varint,3,opt,name=gameStep,proto3,enum=msg.GameStep" json:"gameStep,omitempty"`
	MinRaise             float64       `protobuf:"fixed64,4,opt,name=minRaise,proto3" json:"minRaise,omitempty"`
	PreChips             float64       `protobuf:"fixed64,5,opt,name=preChips,proto3" json:"preChips,omitempty"`
	ActiveId             string        `protobuf:"bytes,6,opt,name=activeId,proto3" json:"activeId,omitempty"`
	Banker               int32         `protobuf:"varint,7,opt,name=banker,proto3" json:"banker,omitempty"`
	BigBlind             float64       `protobuf:"fixed64,8,opt,name=bigBlind,proto3" json:"bigBlind,omitempty"`
	PotMoney             float64       `protobuf:"fixed64,9,opt,name=potMoney,proto3" json:"potMoney,omitempty"`
	IsShowDown           int32         `protobuf:"varint,10,opt,name=isShowDown,proto3" json:"isShowDown,omitempty"`
	IsHaveAllin          bool          `protobuf:"varint,11,opt,name=isHaveAllin,proto3" json:"isHaveAllin,omitempty"`
	PublicCards          []int32       `protobuf:"varint,12,rep,packed,name=publicCards,proto3" json:"publicCards,omitempty"`
	PlayerData           []*PlayerData `protobuf:"bytes,13,rep,name=playerData,proto3" json:"playerData,omitempty"`
	AllPlayer            []*PlayerData `protobuf:"bytes,14,rep,name=AllPlayer,proto3" json:"AllPlayer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RoomData) Reset()         { *m = RoomData{} }
func (m *RoomData) String() string { return proto.CompactTextString(m) }
func (*RoomData) ProtoMessage()    {}
func (*RoomData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{10}
}

func (m *RoomData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomData.Unmarshal(m, b)
}
func (m *RoomData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomData.Marshal(b, m, deterministic)
}
func (m *RoomData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomData.Merge(m, src)
}
func (m *RoomData) XXX_Size() int {
	return xxx_messageInfo_RoomData.Size(m)
}
func (m *RoomData) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomData.DiscardUnknown(m)
}

var xxx_messageInfo_RoomData proto.InternalMessageInfo

func (m *RoomData) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *RoomData) GetCfgId() string {
	if m != nil {
		return m.CfgId
	}
	return ""
}

func (m *RoomData) GetGameStep() GameStep {
	if m != nil {
		return m.GameStep
	}
	return GameStep_Waiting
}

func (m *RoomData) GetMinRaise() float64 {
	if m != nil {
		return m.MinRaise
	}
	return 0
}

func (m *RoomData) GetPreChips() float64 {
	if m != nil {
		return m.PreChips
	}
	return 0
}

func (m *RoomData) GetActiveId() string {
	if m != nil {
		return m.ActiveId
	}
	return ""
}

func (m *RoomData) GetBanker() int32 {
	if m != nil {
		return m.Banker
	}
	return 0
}

func (m *RoomData) GetBigBlind() float64 {
	if m != nil {
		return m.BigBlind
	}
	return 0
}

func (m *RoomData) GetPotMoney() float64 {
	if m != nil {
		return m.PotMoney
	}
	return 0
}

func (m *RoomData) GetIsShowDown() int32 {
	if m != nil {
		return m.IsShowDown
	}
	return 0
}

func (m *RoomData) GetIsHaveAllin() bool {
	if m != nil {
		return m.IsHaveAllin
	}
	return false
}

func (m *RoomData) GetPublicCards() []int32 {
	if m != nil {
		return m.PublicCards
	}
	return nil
}

func (m *RoomData) GetPlayerData() []*PlayerData {
	if m != nil {
		return m.PlayerData
	}
	return nil
}

func (m *RoomData) GetAllPlayer() []*PlayerData {
	if m != nil {
		return m.AllPlayer
	}
	return nil
}

type QuickStart_C2S struct {
	CfgId                string   `protobuf:"bytes,1,opt,name=cfgId,proto3" json:"cfgId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuickStart_C2S) Reset()         { *m = QuickStart_C2S{} }
func (m *QuickStart_C2S) String() string { return proto.CompactTextString(m) }
func (*QuickStart_C2S) ProtoMessage()    {}
func (*QuickStart_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{11}
}

func (m *QuickStart_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuickStart_C2S.Unmarshal(m, b)
}
func (m *QuickStart_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuickStart_C2S.Marshal(b, m, deterministic)
}
func (m *QuickStart_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuickStart_C2S.Merge(m, src)
}
func (m *QuickStart_C2S) XXX_Size() int {
	return xxx_messageInfo_QuickStart_C2S.Size(m)
}
func (m *QuickStart_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_QuickStart_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_QuickStart_C2S proto.InternalMessageInfo

func (m *QuickStart_C2S) GetCfgId() string {
	if m != nil {
		return m.CfgId
	}
	return ""
}

type ChangeTable_C2S struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeTable_C2S) Reset()         { *m = ChangeTable_C2S{} }
func (m *ChangeTable_C2S) String() string { return proto.CompactTextString(m) }
func (*ChangeTable_C2S) ProtoMessage()    {}
func (*ChangeTable_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{12}
}

func (m *ChangeTable_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeTable_C2S.Unmarshal(m, b)
}
func (m *ChangeTable_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeTable_C2S.Marshal(b, m, deterministic)
}
func (m *ChangeTable_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeTable_C2S.Merge(m, src)
}
func (m *ChangeTable_C2S) XXX_Size() int {
	return xxx_messageInfo_ChangeTable_C2S.Size(m)
}
func (m *ChangeTable_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeTable_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeTable_C2S proto.InternalMessageInfo

type JoinRoom_S2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,opt,name=roomData,proto3" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *JoinRoom_S2C) Reset()         { *m = JoinRoom_S2C{} }
func (m *JoinRoom_S2C) String() string { return proto.CompactTextString(m) }
func (*JoinRoom_S2C) ProtoMessage()    {}
func (*JoinRoom_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{13}
}

func (m *JoinRoom_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoom_S2C.Unmarshal(m, b)
}
func (m *JoinRoom_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoom_S2C.Marshal(b, m, deterministic)
}
func (m *JoinRoom_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoom_S2C.Merge(m, src)
}
func (m *JoinRoom_S2C) XXX_Size() int {
	return xxx_messageInfo_JoinRoom_S2C.Size(m)
}
func (m *JoinRoom_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoom_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoom_S2C proto.InternalMessageInfo

func (m *JoinRoom_S2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

type EnterRoom_S2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,opt,name=roomData,proto3" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EnterRoom_S2C) Reset()         { *m = EnterRoom_S2C{} }
func (m *EnterRoom_S2C) String() string { return proto.CompactTextString(m) }
func (*EnterRoom_S2C) ProtoMessage()    {}
func (*EnterRoom_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{14}
}

func (m *EnterRoom_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterRoom_S2C.Unmarshal(m, b)
}
func (m *EnterRoom_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterRoom_S2C.Marshal(b, m, deterministic)
}
func (m *EnterRoom_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterRoom_S2C.Merge(m, src)
}
func (m *EnterRoom_S2C) XXX_Size() int {
	return xxx_messageInfo_EnterRoom_S2C.Size(m)
}
func (m *EnterRoom_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterRoom_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_EnterRoom_S2C proto.InternalMessageInfo

func (m *EnterRoom_S2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

type NoticeJoin_S2C struct {
	PlayerData           *PlayerData `protobuf:"bytes,1,opt,name=playerData,proto3" json:"playerData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NoticeJoin_S2C) Reset()         { *m = NoticeJoin_S2C{} }
func (m *NoticeJoin_S2C) String() string { return proto.CompactTextString(m) }
func (*NoticeJoin_S2C) ProtoMessage()    {}
func (*NoticeJoin_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{15}
}

func (m *NoticeJoin_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeJoin_S2C.Unmarshal(m, b)
}
func (m *NoticeJoin_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeJoin_S2C.Marshal(b, m, deterministic)
}
func (m *NoticeJoin_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeJoin_S2C.Merge(m, src)
}
func (m *NoticeJoin_S2C) XXX_Size() int {
	return xxx_messageInfo_NoticeJoin_S2C.Size(m)
}
func (m *NoticeJoin_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeJoin_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeJoin_S2C proto.InternalMessageInfo

func (m *NoticeJoin_S2C) GetPlayerData() *PlayerData {
	if m != nil {
		return m.PlayerData
	}
	return nil
}

type LeaveRoom_C2S struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoom_C2S) Reset()         { *m = LeaveRoom_C2S{} }
func (m *LeaveRoom_C2S) String() string { return proto.CompactTextString(m) }
func (*LeaveRoom_C2S) ProtoMessage()    {}
func (*LeaveRoom_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{16}
}

func (m *LeaveRoom_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoom_C2S.Unmarshal(m, b)
}
func (m *LeaveRoom_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoom_C2S.Marshal(b, m, deterministic)
}
func (m *LeaveRoom_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoom_C2S.Merge(m, src)
}
func (m *LeaveRoom_C2S) XXX_Size() int {
	return xxx_messageInfo_LeaveRoom_C2S.Size(m)
}
func (m *LeaveRoom_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoom_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoom_C2S proto.InternalMessageInfo

type LeaveRoom_S2C struct {
	PlayerData           *PlayerData `protobuf:"bytes,1,opt,name=playerData,proto3" json:"playerData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LeaveRoom_S2C) Reset()         { *m = LeaveRoom_S2C{} }
func (m *LeaveRoom_S2C) String() string { return proto.CompactTextString(m) }
func (*LeaveRoom_S2C) ProtoMessage()    {}
func (*LeaveRoom_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{17}
}

func (m *LeaveRoom_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoom_S2C.Unmarshal(m, b)
}
func (m *LeaveRoom_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoom_S2C.Marshal(b, m, deterministic)
}
func (m *LeaveRoom_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoom_S2C.Merge(m, src)
}
func (m *LeaveRoom_S2C) XXX_Size() int {
	return xxx_messageInfo_LeaveRoom_S2C.Size(m)
}
func (m *LeaveRoom_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoom_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoom_S2C proto.InternalMessageInfo

func (m *LeaveRoom_S2C) GetPlayerData() *PlayerData {
	if m != nil {
		return m.PlayerData
	}
	return nil
}

type SitDown_C2S struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SitDown_C2S) Reset()         { *m = SitDown_C2S{} }
func (m *SitDown_C2S) String() string { return proto.CompactTextString(m) }
func (*SitDown_C2S) ProtoMessage()    {}
func (*SitDown_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{18}
}

func (m *SitDown_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SitDown_C2S.Unmarshal(m, b)
}
func (m *SitDown_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SitDown_C2S.Marshal(b, m, deterministic)
}
func (m *SitDown_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SitDown_C2S.Merge(m, src)
}
func (m *SitDown_C2S) XXX_Size() int {
	return xxx_messageInfo_SitDown_C2S.Size(m)
}
func (m *SitDown_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_SitDown_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_SitDown_C2S proto.InternalMessageInfo

type SitDown_S2C struct {
	PlayerData           *PlayerData `protobuf:"bytes,1,opt,name=playerData,proto3" json:"playerData,omitempty"`
	RoomData             *RoomData   `protobuf:"bytes,2,opt,name=roomData,proto3" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SitDown_S2C) Reset()         { *m = SitDown_S2C{} }
func (m *SitDown_S2C) String() string { return proto.CompactTextString(m) }
func (*SitDown_S2C) ProtoMessage()    {}
func (*SitDown_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{19}
}

func (m *SitDown_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SitDown_S2C.Unmarshal(m, b)
}
func (m *SitDown_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SitDown_S2C.Marshal(b, m, deterministic)
}
func (m *SitDown_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SitDown_S2C.Merge(m, src)
}
func (m *SitDown_S2C) XXX_Size() int {
	return xxx_messageInfo_SitDown_S2C.Size(m)
}
func (m *SitDown_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_SitDown_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_SitDown_S2C proto.InternalMessageInfo

func (m *SitDown_S2C) GetPlayerData() *PlayerData {
	if m != nil {
		return m.PlayerData
	}
	return nil
}

func (m *SitDown_S2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

type StandUp_C2S struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StandUp_C2S) Reset()         { *m = StandUp_C2S{} }
func (m *StandUp_C2S) String() string { return proto.CompactTextString(m) }
func (*StandUp_C2S) ProtoMessage()    {}
func (*StandUp_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{20}
}

func (m *StandUp_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StandUp_C2S.Unmarshal(m, b)
}
func (m *StandUp_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StandUp_C2S.Marshal(b, m, deterministic)
}
func (m *StandUp_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StandUp_C2S.Merge(m, src)
}
func (m *StandUp_C2S) XXX_Size() int {
	return xxx_messageInfo_StandUp_C2S.Size(m)
}
func (m *StandUp_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_StandUp_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_StandUp_C2S proto.InternalMessageInfo

type StandUp_S2C struct {
	PlayerData           *PlayerData `protobuf:"bytes,1,opt,name=playerData,proto3" json:"playerData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StandUp_S2C) Reset()         { *m = StandUp_S2C{} }
func (m *StandUp_S2C) String() string { return proto.CompactTextString(m) }
func (*StandUp_S2C) ProtoMessage()    {}
func (*StandUp_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{21}
}

func (m *StandUp_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StandUp_S2C.Unmarshal(m, b)
}
func (m *StandUp_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StandUp_S2C.Marshal(b, m, deterministic)
}
func (m *StandUp_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StandUp_S2C.Merge(m, src)
}
func (m *StandUp_S2C) XXX_Size() int {
	return xxx_messageInfo_StandUp_S2C.Size(m)
}
func (m *StandUp_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_StandUp_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_StandUp_S2C proto.InternalMessageInfo

func (m *StandUp_S2C) GetPlayerData() *PlayerData {
	if m != nil {
		return m.PlayerData
	}
	return nil
}

type PlayerAction_C2S struct {
	BetAmount            float64      `protobuf:"fixed64,1,opt,name=betAmount,proto3" json:"betAmount,omitempty"`
	Action               ActionStatus `protobuf:"varint,2,opt,name=action,proto3,enum=msg.ActionStatus" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PlayerAction_C2S) Reset()         { *m = PlayerAction_C2S{} }
func (m *PlayerAction_C2S) String() string { return proto.CompactTextString(m) }
func (*PlayerAction_C2S) ProtoMessage()    {}
func (*PlayerAction_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{22}
}

func (m *PlayerAction_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerAction_C2S.Unmarshal(m, b)
}
func (m *PlayerAction_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerAction_C2S.Marshal(b, m, deterministic)
}
func (m *PlayerAction_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerAction_C2S.Merge(m, src)
}
func (m *PlayerAction_C2S) XXX_Size() int {
	return xxx_messageInfo_PlayerAction_C2S.Size(m)
}
func (m *PlayerAction_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerAction_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerAction_C2S proto.InternalMessageInfo

func (m *PlayerAction_C2S) GetBetAmount() float64 {
	if m != nil {
		return m.BetAmount
	}
	return 0
}

func (m *PlayerAction_C2S) GetAction() ActionStatus {
	if m != nil {
		return m.Action
	}
	return ActionStatus_WAITING
}

type PlayerAction_S2C struct {
	Id                   string       `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Chair                int32        `protobuf:"varint,2,opt,name=chair,proto3" json:"chair,omitempty"`
	Chips                float64      `protobuf:"fixed64,3,opt,name=chips,proto3" json:"chips,omitempty"`
	DownBet              float64      `protobuf:"fixed64,4,opt,name=downBet,proto3" json:"downBet,omitempty"`
	PreChips             float64      `protobuf:"fixed64,5,opt,name=preChips,proto3" json:"preChips,omitempty"`
	PotMoney             float64      `protobuf:"fixed64,6,opt,name=potMoney,proto3" json:"potMoney,omitempty"`
	ActionType           ActionStatus `protobuf:"varint,7,opt,name=actionType,proto3,enum=msg.ActionStatus" json:"actionType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PlayerAction_S2C) Reset()         { *m = PlayerAction_S2C{} }
func (m *PlayerAction_S2C) String() string { return proto.CompactTextString(m) }
func (*PlayerAction_S2C) ProtoMessage()    {}
func (*PlayerAction_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{23}
}

func (m *PlayerAction_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerAction_S2C.Unmarshal(m, b)
}
func (m *PlayerAction_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerAction_S2C.Marshal(b, m, deterministic)
}
func (m *PlayerAction_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerAction_S2C.Merge(m, src)
}
func (m *PlayerAction_S2C) XXX_Size() int {
	return xxx_messageInfo_PlayerAction_S2C.Size(m)
}
func (m *PlayerAction_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerAction_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerAction_S2C proto.InternalMessageInfo

func (m *PlayerAction_S2C) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlayerAction_S2C) GetChair() int32 {
	if m != nil {
		return m.Chair
	}
	return 0
}

func (m *PlayerAction_S2C) GetChips() float64 {
	if m != nil {
		return m.Chips
	}
	return 0
}

func (m *PlayerAction_S2C) GetDownBet() float64 {
	if m != nil {
		return m.DownBet
	}
	return 0
}

func (m *PlayerAction_S2C) GetPreChips() float64 {
	if m != nil {
		return m.PreChips
	}
	return 0
}

func (m *PlayerAction_S2C) GetPotMoney() float64 {
	if m != nil {
		return m.PotMoney
	}
	return 0
}

func (m *PlayerAction_S2C) GetActionType() ActionStatus {
	if m != nil {
		return m.ActionType
	}
	return ActionStatus_WAITING
}

// 当前玩家行动变更
type PlayerActionChange_S2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,opt,name=roomData,proto3" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlayerActionChange_S2C) Reset()         { *m = PlayerActionChange_S2C{} }
func (m *PlayerActionChange_S2C) String() string { return proto.CompactTextString(m) }
func (*PlayerActionChange_S2C) ProtoMessage()    {}
func (*PlayerActionChange_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{24}
}

func (m *PlayerActionChange_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerActionChange_S2C.Unmarshal(m, b)
}
func (m *PlayerActionChange_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerActionChange_S2C.Marshal(b, m, deterministic)
}
func (m *PlayerActionChange_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerActionChange_S2C.Merge(m, src)
}
func (m *PlayerActionChange_S2C) XXX_Size() int {
	return xxx_messageInfo_PlayerActionChange_S2C.Size(m)
}
func (m *PlayerActionChange_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerActionChange_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerActionChange_S2C proto.InternalMessageInfo

func (m *PlayerActionChange_S2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

// 玩家添加筹码
type AddChips_C2S struct {
	AddChips             float64  `protobuf:"fixed64,1,opt,name=addChips,proto3" json:"addChips,omitempty"`
	SysBuyChips          int32    `protobuf:"varint,2,opt,name=sysBuyChips,proto3" json:"sysBuyChips,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddChips_C2S) Reset()         { *m = AddChips_C2S{} }
func (m *AddChips_C2S) String() string { return proto.CompactTextString(m) }
func (*AddChips_C2S) ProtoMessage()    {}
func (*AddChips_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{25}
}

func (m *AddChips_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddChips_C2S.Unmarshal(m, b)
}
func (m *AddChips_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddChips_C2S.Marshal(b, m, deterministic)
}
func (m *AddChips_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddChips_C2S.Merge(m, src)
}
func (m *AddChips_C2S) XXX_Size() int {
	return xxx_messageInfo_AddChips_C2S.Size(m)
}
func (m *AddChips_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_AddChips_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_AddChips_C2S proto.InternalMessageInfo

func (m *AddChips_C2S) GetAddChips() float64 {
	if m != nil {
		return m.AddChips
	}
	return 0
}

func (m *AddChips_C2S) GetSysBuyChips() int32 {
	if m != nil {
		return m.SysBuyChips
	}
	return 0
}

type AddChips_S2C struct {
	Chair                int32    `protobuf:"varint,1,opt,name=chair,proto3" json:"chair,omitempty"`
	AddChips             float64  `protobuf:"fixed64,2,opt,name=addChips,proto3" json:"addChips,omitempty"`
	Chips                float64  `protobuf:"fixed64,3,opt,name=chips,proto3" json:"chips,omitempty"`
	RoomChips            float64  `protobuf:"fixed64,4,opt,name=roomChips,proto3" json:"roomChips,omitempty"`
	SysBuyChips          int32    `protobuf:"varint,5,opt,name=sysBuyChips,proto3" json:"sysBuyChips,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddChips_S2C) Reset()         { *m = AddChips_S2C{} }
func (m *AddChips_S2C) String() string { return proto.CompactTextString(m) }
func (*AddChips_S2C) ProtoMessage()    {}
func (*AddChips_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{26}
}

func (m *AddChips_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddChips_S2C.Unmarshal(m, b)
}
func (m *AddChips_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddChips_S2C.Marshal(b, m, deterministic)
}
func (m *AddChips_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddChips_S2C.Merge(m, src)
}
func (m *AddChips_S2C) XXX_Size() int {
	return xxx_messageInfo_AddChips_S2C.Size(m)
}
func (m *AddChips_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_AddChips_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_AddChips_S2C proto.InternalMessageInfo

func (m *AddChips_S2C) GetChair() int32 {
	if m != nil {
		return m.Chair
	}
	return 0
}

func (m *AddChips_S2C) GetAddChips() float64 {
	if m != nil {
		return m.AddChips
	}
	return 0
}

func (m *AddChips_S2C) GetChips() float64 {
	if m != nil {
		return m.Chips
	}
	return 0
}

func (m *AddChips_S2C) GetRoomChips() float64 {
	if m != nil {
		return m.RoomChips
	}
	return 0
}

func (m *AddChips_S2C) GetSysBuyChips() int32 {
	if m != nil {
		return m.SysBuyChips
	}
	return 0
}

// 阶段变更
type GameStepChange_S2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,opt,name=roomData,proto3" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GameStepChange_S2C) Reset()         { *m = GameStepChange_S2C{} }
func (m *GameStepChange_S2C) String() string { return proto.CompactTextString(m) }
func (*GameStepChange_S2C) ProtoMessage()    {}
func (*GameStepChange_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{27}
}

func (m *GameStepChange_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameStepChange_S2C.Unmarshal(m, b)
}
func (m *GameStepChange_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameStepChange_S2C.Marshal(b, m, deterministic)
}
func (m *GameStepChange_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameStepChange_S2C.Merge(m, src)
}
func (m *GameStepChange_S2C) XXX_Size() int {
	return xxx_messageInfo_GameStepChange_S2C.Size(m)
}
func (m *GameStepChange_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_GameStepChange_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_GameStepChange_S2C proto.InternalMessageInfo

func (m *GameStepChange_S2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

// 游戏结算数据
type ResultGameData_S2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,opt,name=roomData,proto3" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResultGameData_S2C) Reset()         { *m = ResultGameData_S2C{} }
func (m *ResultGameData_S2C) String() string { return proto.CompactTextString(m) }
func (*ResultGameData_S2C) ProtoMessage()    {}
func (*ResultGameData_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{28}
}

func (m *ResultGameData_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultGameData_S2C.Unmarshal(m, b)
}
func (m *ResultGameData_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultGameData_S2C.Marshal(b, m, deterministic)
}
func (m *ResultGameData_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultGameData_S2C.Merge(m, src)
}
func (m *ResultGameData_S2C) XXX_Size() int {
	return xxx_messageInfo_ResultGameData_S2C.Size(m)
}
func (m *ResultGameData_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultGameData_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_ResultGameData_S2C proto.InternalMessageInfo

func (m *ResultGameData_S2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

// 游戏准备时间
type ReadyTime_S2C struct {
	ReadyTime            int32    `protobuf:"varint,1,opt,name=readyTime,proto3" json:"readyTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadyTime_S2C) Reset()         { *m = ReadyTime_S2C{} }
func (m *ReadyTime_S2C) String() string { return proto.CompactTextString(m) }
func (*ReadyTime_S2C) ProtoMessage()    {}
func (*ReadyTime_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{29}
}

func (m *ReadyTime_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadyTime_S2C.Unmarshal(m, b)
}
func (m *ReadyTime_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadyTime_S2C.Marshal(b, m, deterministic)
}
func (m *ReadyTime_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadyTime_S2C.Merge(m, src)
}
func (m *ReadyTime_S2C) XXX_Size() int {
	return xxx_messageInfo_ReadyTime_S2C.Size(m)
}
func (m *ReadyTime_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadyTime_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_ReadyTime_S2C proto.InternalMessageInfo

func (m *ReadyTime_S2C) GetReadyTime() int32 {
	if m != nil {
		return m.ReadyTime
	}
	return 0
}

// 游戏结算时间
type SettleTime_S2C struct {
	SettleTime           int32    `protobuf:"varint,1,opt,name=settleTime,proto3" json:"settleTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettleTime_S2C) Reset()         { *m = SettleTime_S2C{} }
func (m *SettleTime_S2C) String() string { return proto.CompactTextString(m) }
func (*SettleTime_S2C) ProtoMessage()    {}
func (*SettleTime_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{30}
}

func (m *SettleTime_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettleTime_S2C.Unmarshal(m, b)
}
func (m *SettleTime_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettleTime_S2C.Marshal(b, m, deterministic)
}
func (m *SettleTime_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettleTime_S2C.Merge(m, src)
}
func (m *SettleTime_S2C) XXX_Size() int {
	return xxx_messageInfo_SettleTime_S2C.Size(m)
}
func (m *SettleTime_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_SettleTime_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_SettleTime_S2C proto.InternalMessageInfo

func (m *SettleTime_S2C) GetSettleTime() int32 {
	if m != nil {
		return m.SettleTime
	}
	return 0
}

// 发牌时间
type PushCardTime_S2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,opt,name=roomData,proto3" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PushCardTime_S2C) Reset()         { *m = PushCardTime_S2C{} }
func (m *PushCardTime_S2C) String() string { return proto.CompactTextString(m) }
func (*PushCardTime_S2C) ProtoMessage()    {}
func (*PushCardTime_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{31}
}

func (m *PushCardTime_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushCardTime_S2C.Unmarshal(m, b)
}
func (m *PushCardTime_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushCardTime_S2C.Marshal(b, m, deterministic)
}
func (m *PushCardTime_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushCardTime_S2C.Merge(m, src)
}
func (m *PushCardTime_S2C) XXX_Size() int {
	return xxx_messageInfo_PushCardTime_S2C.Size(m)
}
func (m *PushCardTime_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_PushCardTime_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_PushCardTime_S2C proto.InternalMessageInfo

func (m *PushCardTime_S2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

// 房间状态
type RoomStatus_C2S struct {
	CfgId                string   `protobuf:"bytes,1,opt,name=cfgId,proto3" json:"cfgId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomStatus_C2S) Reset()         { *m = RoomStatus_C2S{} }
func (m *RoomStatus_C2S) String() string { return proto.CompactTextString(m) }
func (*RoomStatus_C2S) ProtoMessage()    {}
func (*RoomStatus_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{32}
}

func (m *RoomStatus_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomStatus_C2S.Unmarshal(m, b)
}
func (m *RoomStatus_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomStatus_C2S.Marshal(b, m, deterministic)
}
func (m *RoomStatus_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomStatus_C2S.Merge(m, src)
}
func (m *RoomStatus_C2S) XXX_Size() int {
	return xxx_messageInfo_RoomStatus_C2S.Size(m)
}
func (m *RoomStatus_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomStatus_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_RoomStatus_C2S proto.InternalMessageInfo

func (m *RoomStatus_C2S) GetCfgId() string {
	if m != nil {
		return m.CfgId
	}
	return ""
}

type RoomStatus_S2C struct {
	CfgId                string   `protobuf:"bytes,1,opt,name=cfgId,proto3" json:"cfgId,omitempty"`
	RoomIdNow            string   `protobuf:"bytes,2,opt,name=RoomIdNow,proto3" json:"RoomIdNow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomStatus_S2C) Reset()         { *m = RoomStatus_S2C{} }
func (m *RoomStatus_S2C) String() string { return proto.CompactTextString(m) }
func (*RoomStatus_S2C) ProtoMessage()    {}
func (*RoomStatus_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{33}
}

func (m *RoomStatus_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomStatus_S2C.Unmarshal(m, b)
}
func (m *RoomStatus_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomStatus_S2C.Marshal(b, m, deterministic)
}
func (m *RoomStatus_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomStatus_S2C.Merge(m, src)
}
func (m *RoomStatus_S2C) XXX_Size() int {
	return xxx_messageInfo_RoomStatus_S2C.Size(m)
}
func (m *RoomStatus_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomStatus_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_RoomStatus_S2C proto.InternalMessageInfo

func (m *RoomStatus_S2C) GetCfgId() string {
	if m != nil {
		return m.CfgId
	}
	return ""
}

func (m *RoomStatus_S2C) GetRoomIdNow() string {
	if m != nil {
		return m.RoomIdNow
	}
	return ""
}

// 表情发送
type EmojiChat_C2S struct {
	ActNum               int32    `protobuf:"varint,1,opt,name=actNum,proto3" json:"actNum,omitempty"`
	GoalChair            int32    `protobuf:"varint,2,opt,name=goalChair,proto3" json:"goalChair,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmojiChat_C2S) Reset()         { *m = EmojiChat_C2S{} }
func (m *EmojiChat_C2S) String() string { return proto.CompactTextString(m) }
func (*EmojiChat_C2S) ProtoMessage()    {}
func (*EmojiChat_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{34}
}

func (m *EmojiChat_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmojiChat_C2S.Unmarshal(m, b)
}
func (m *EmojiChat_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmojiChat_C2S.Marshal(b, m, deterministic)
}
func (m *EmojiChat_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmojiChat_C2S.Merge(m, src)
}
func (m *EmojiChat_C2S) XXX_Size() int {
	return xxx_messageInfo_EmojiChat_C2S.Size(m)
}
func (m *EmojiChat_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_EmojiChat_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_EmojiChat_C2S proto.InternalMessageInfo

func (m *EmojiChat_C2S) GetActNum() int32 {
	if m != nil {
		return m.ActNum
	}
	return 0
}

func (m *EmojiChat_C2S) GetGoalChair() int32 {
	if m != nil {
		return m.GoalChair
	}
	return 0
}

// 表情发送
type EmojiChat_S2C struct {
	ActNum               int32    `protobuf:"varint,1,opt,name=actNum,proto3" json:"actNum,omitempty"`
	ActChair             int32    `protobuf:"varint,2,opt,name=actChair,proto3" json:"actChair,omitempty"`
	GoalChair            int32    `protobuf:"varint,3,opt,name=goalChair,proto3" json:"goalChair,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmojiChat_S2C) Reset()         { *m = EmojiChat_S2C{} }
func (m *EmojiChat_S2C) String() string { return proto.CompactTextString(m) }
func (*EmojiChat_S2C) ProtoMessage()    {}
func (*EmojiChat_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{35}
}

func (m *EmojiChat_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmojiChat_S2C.Unmarshal(m, b)
}
func (m *EmojiChat_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmojiChat_S2C.Marshal(b, m, deterministic)
}
func (m *EmojiChat_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmojiChat_S2C.Merge(m, src)
}
func (m *EmojiChat_S2C) XXX_Size() int {
	return xxx_messageInfo_EmojiChat_S2C.Size(m)
}
func (m *EmojiChat_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_EmojiChat_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_EmojiChat_S2C proto.InternalMessageInfo

func (m *EmojiChat_S2C) GetActNum() int32 {
	if m != nil {
		return m.ActNum
	}
	return 0
}

func (m *EmojiChat_S2C) GetActChair() int32 {
	if m != nil {
		return m.ActChair
	}
	return 0
}

func (m *EmojiChat_S2C) GetGoalChair() int32 {
	if m != nil {
		return m.GoalChair
	}
	return 0
}

type PiPeiPlayer_S2C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PiPeiPlayer_S2C) Reset()         { *m = PiPeiPlayer_S2C{} }
func (m *PiPeiPlayer_S2C) String() string { return proto.CompactTextString(m) }
func (*PiPeiPlayer_S2C) ProtoMessage()    {}
func (*PiPeiPlayer_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{36}
}

func (m *PiPeiPlayer_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PiPeiPlayer_S2C.Unmarshal(m, b)
}
func (m *PiPeiPlayer_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PiPeiPlayer_S2C.Marshal(b, m, deterministic)
}
func (m *PiPeiPlayer_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PiPeiPlayer_S2C.Merge(m, src)
}
func (m *PiPeiPlayer_S2C) XXX_Size() int {
	return xxx_messageInfo_PiPeiPlayer_S2C.Size(m)
}
func (m *PiPeiPlayer_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_PiPeiPlayer_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_PiPeiPlayer_S2C proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("msg.MessageID", MessageID_name, MessageID_value)
	proto.RegisterEnum("msg.ErrorMsg", ErrorMsg_name, ErrorMsg_value)
	proto.RegisterEnum("msg.CardSuit", CardSuit_name, CardSuit_value)
	proto.RegisterEnum("msg.GameStep", GameStep_name, GameStep_value)
	proto.RegisterEnum("msg.ActionStatus", ActionStatus_name, ActionStatus_value)
	proto.RegisterEnum("msg.BlindType", BlindType_name, BlindType_value)
	proto.RegisterType((*Ping)(nil), "msg.Ping")
	proto.RegisterType((*Pong)(nil), "msg.Pong")
	proto.RegisterType((*Error_S2C)(nil), "msg.Error_S2C")
	proto.RegisterType((*Login_C2S)(nil), "msg.Login_C2S")
	proto.RegisterType((*PlayerInfo)(nil), "msg.PlayerInfo")
	proto.RegisterType((*Login_S2C)(nil), "msg.Login_S2C")
	proto.RegisterType((*Logout_C2S)(nil), "msg.Logout_C2S")
	proto.RegisterType((*Logout_S2C)(nil), "msg.Logout_S2C")
	proto.RegisterType((*CardSuitData)(nil), "msg.CardSuitData")
	proto.RegisterType((*PlayerData)(nil), "msg.PlayerData")
	proto.RegisterType((*RoomData)(nil), "msg.RoomData")
	proto.RegisterType((*QuickStart_C2S)(nil), "msg.QuickStart_C2S")
	proto.RegisterType((*ChangeTable_C2S)(nil), "msg.ChangeTable_C2S")
	proto.RegisterType((*JoinRoom_S2C)(nil), "msg.JoinRoom_S2C")
	proto.RegisterType((*EnterRoom_S2C)(nil), "msg.EnterRoom_S2C")
	proto.RegisterType((*NoticeJoin_S2C)(nil), "msg.NoticeJoin_S2C")
	proto.RegisterType((*LeaveRoom_C2S)(nil), "msg.LeaveRoom_C2S")
	proto.RegisterType((*LeaveRoom_S2C)(nil), "msg.LeaveRoom_S2C")
	proto.RegisterType((*SitDown_C2S)(nil), "msg.SitDown_C2S")
	proto.RegisterType((*SitDown_S2C)(nil), "msg.SitDown_S2C")
	proto.RegisterType((*StandUp_C2S)(nil), "msg.StandUp_C2S")
	proto.RegisterType((*StandUp_S2C)(nil), "msg.StandUp_S2C")
	proto.RegisterType((*PlayerAction_C2S)(nil), "msg.PlayerAction_C2S")
	proto.RegisterType((*PlayerAction_S2C)(nil), "msg.PlayerAction_S2C")
	proto.RegisterType((*PlayerActionChange_S2C)(nil), "msg.PlayerActionChange_S2C")
	proto.RegisterType((*AddChips_C2S)(nil), "msg.AddChips_C2S")
	proto.RegisterType((*AddChips_S2C)(nil), "msg.AddChips_S2C")
	proto.RegisterType((*GameStepChange_S2C)(nil), "msg.GameStepChange_S2C")
	proto.RegisterType((*ResultGameData_S2C)(nil), "msg.ResultGameData_S2C")
	proto.RegisterType((*ReadyTime_S2C)(nil), "msg.ReadyTime_S2C")
	proto.RegisterType((*SettleTime_S2C)(nil), "msg.SettleTime_S2C")
	proto.RegisterType((*PushCardTime_S2C)(nil), "msg.PushCardTime_S2C")
	proto.RegisterType((*RoomStatus_C2S)(nil), "msg.RoomStatus_C2S")
	proto.RegisterType((*RoomStatus_S2C)(nil), "msg.RoomStatus_S2C")
	proto.RegisterType((*EmojiChat_C2S)(nil), "msg.EmojiChat_C2S")
	proto.RegisterType((*EmojiChat_S2C)(nil), "msg.EmojiChat_S2C")
	proto.RegisterType((*PiPeiPlayer_S2C)(nil), "msg.PiPeiPlayer_S2C")
}

func init() {
	proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899)
}

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 1823 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x58, 0xdd, 0x72, 0xdb, 0xb8,
	0x15, 0x0e, 0x25, 0xcb, 0x96, 0x8e, 0x7e, 0x0c, 0x23, 0x8e, 0x97, 0x9b, 0xa6, 0xa9, 0x87, 0x9d,
	0xc9, 0x38, 0x9e, 0xee, 0x6e, 0xeb, 0x4e, 0x2f, 0xb6, 0xd3, 0x76, 0x2b, 0xcb, 0x76, 0xa2, 0xc6,
	0x56, 0xb4, 0x94, 0x33, 0xc9, 0x4c, 0x2f, 0x3c, 0xb0, 0x04, 0x53, 0x58, 0x53, 0x84, 0x86, 0x04,
	0x9d, 0xf1, 0x33, 0xf4, 0xbe, 0xef, 0xd0, 0x27, 0xe9, 0x45, 0x2f, 0xfb, 0x1a, 0x7d, 0x80, 0x5e,
	0x76, 0x0e, 0x48, 0x90, 0xa0, 0xec, 0xa4, 0x13, 0xdf, 0xe9, 0xfb, 0xce, 0xc1, 0xc1, 0xc1, 0xc1,
	0xf9, 0x21, 0x04, 0xad, 0x45, 0x12, 0x7c, 0xbb, 0x8c, 0xa5, 0x92, 0xb4, 0xbe, 0x48, 0x02, 0x6f,
	0x1d, 0xd6, 0xc6, 0x22, 0x0a, 0xbc, 0x17, 0xb0, 0x36, 0x96, 0x51, 0x40, 0x9f, 0x03, 0x24, 0x3c,
	0xbe, 0xe1, 0xf1, 0xb9, 0x58, 0x70, 0xd7, 0xd9, 0x75, 0xf6, 0xea, 0xbe, 0xc5, 0x78, 0x47, 0xd0,
	0x3a, 0x8e, 0x63, 0x19, 0x5f, 0x4c, 0x0e, 0x06, 0xf4, 0x97, 0xd0, 0xe0, 0x08, 0xb4, 0x5e, 0xef,
	0xa0, 0xfb, 0x2d, 0x1a, 0xd7, 0xe2, 0xb3, 0x24, 0xf0, 0x33, 0x19, 0xa5, 0xb0, 0x36, 0x63, 0x8a,
	0xb9, 0xb5, 0x5d, 0x67, 0xaf, 0xe5, 0xeb, 0xdf, 0xde, 0x19, 0xb4, 0x4e, 0x65, 0x20, 0xa2, 0x8b,
	0xc1, 0xc1, 0x84, 0xf6, 0xa0, 0x36, 0x9c, 0x69, 0x13, 0x2d, 0xbf, 0x36, 0x9c, 0xd1, 0xa7, 0xd0,
	0x1c, 0xb3, 0x24, 0x79, 0x2f, 0xe3, 0x59, 0xbe, 0xa8, 0xc0, 0x74, 0x1b, 0x1a, 0xe7, 0xf2, 0x9a,
	0x47, 0x6e, 0x5d, 0x0b, 0x32, 0xe0, 0x85, 0x00, 0xe3, 0x90, 0xdd, 0xf2, 0x78, 0x18, 0x5d, 0xc9,
	0xfb, 0xec, 0x45, 0x62, 0x7a, 0x3d, 0x62, 0x0b, 0x6e, 0xec, 0x19, 0x4c, 0x5d, 0xd8, 0x98, 0x73,
	0x36, 0x1b, 0x2e, 0x82, 0xdc, 0xa2, 0x81, 0x28, 0x61, 0xd3, 0xa9, 0x4c, 0x23, 0xe5, 0xae, 0xed,
	0x3a, 0x7b, 0x8e, 0x6f, 0xa0, 0xf7, 0x07, 0xe3, 0x3c, 0x86, 0xe0, 0x3b, 0x80, 0x65, 0xb1, 0xb5,
	0xde, 0xb4, 0x7d, 0xb0, 0xa9, 0xe3, 0x50, 0x7a, 0xe4, 0x5b, 0x2a, 0x5e, 0x07, 0xe0, 0x54, 0x06,
	0x32, 0x55, 0x78, 0x76, 0x0b, 0x4d, 0x0e, 0x06, 0xde, 0xdf, 0x1c, 0xe8, 0x0c, 0x58, 0x3c, 0x9b,
	0xa4, 0x42, 0x1d, 0x31, 0xc5, 0xa8, 0x07, 0x9d, 0x39, 0x8b, 0x66, 0xc8, 0xbd, 0xe1, 0xb7, 0x89,
	0xeb, 0xec, 0xd6, 0xf7, 0x1a, 0x7e, 0x85, 0xa3, 0x2f, 0xa0, 0xb7, 0x4c, 0x2f, 0x43, 0x31, 0x2d,
	0xb4, 0x6a, 0x5a, 0x6b, 0x85, 0xa5, 0xdf, 0x41, 0x3b, 0x49, 0x85, 0x1a, 0x33, 0xa5, 0x78, 0x9c,
	0x05, 0xd0, 0x5c, 0x99, 0xd9, 0xd3, 0xb7, 0x35, 0xbc, 0x7f, 0x36, 0x4c, 0x58, 0xb5, 0x2f, 0x5f,
	0x7a, 0x52, 0xbc, 0xab, 0xe9, 0x9c, 0x89, 0x58, 0x07, 0xbd, 0xe1, 0x67, 0x40, 0x27, 0x98, 0x62,
	0xd1, 0xec, 0xdd, 0x78, 0x94, 0x2e, 0xb4, 0x17, 0x0d, 0xdf, 0x62, 0xb2, 0x55, 0x62, 0x99, 0xe4,
	0x51, 0xcf, 0x00, 0x7d, 0x06, 0xad, 0x58, 0xca, 0xc5, 0x40, 0x4b, 0x1a, 0x5a, 0x52, 0x12, 0xf4,
	0x77, 0xd0, 0x61, 0x53, 0x25, 0x64, 0x34, 0x51, 0x4c, 0xa5, 0x89, 0xbb, 0xae, 0xcf, 0xb6, 0xa5,
	0x9d, 0xeb, 0x5b, 0x02, 0xbf, 0xa2, 0x86, 0x89, 0x11, 0xb0, 0x05, 0x9f, 0x28, 0xbe, 0x74, 0x37,
	0xb4, 0x23, 0x05, 0x46, 0xd9, 0x4c, 0x7e, 0x8c, 0x0e, 0xb9, 0x4a, 0xdc, 0xa6, 0xde, 0xaf, 0xc0,
	0x74, 0x17, 0xda, 0x61, 0x1a, 0x1d, 0x19, 0x71, 0x4b, 0x8b, 0x6d, 0x0a, 0xef, 0x4d, 0x49, 0xc5,
	0xc2, 0x9c, 0x70, 0x41, 0xab, 0x54, 0x38, 0x3c, 0x92, 0xb9, 0xc7, 0xc4, 0x6d, 0xeb, 0x2b, 0x2b,
	0x09, 0x3c, 0xd2, 0xd4, 0xca, 0x04, 0xb7, 0xa3, 0xe3, 0xbd, 0x55, 0xb9, 0x2e, 0x14, 0xf8, 0x15,
	0x35, 0x74, 0x2d, 0xe6, 0x49, 0x1a, 0xaa, 0x33, 0x19, 0xf1, 0x5b, 0xb7, 0x9b, 0xb9, 0x66, 0x51,
	0xf4, 0x57, 0xd0, 0xba, 0x0c, 0x45, 0x34, 0x3b, 0xbf, 0x5d, 0x72, 0xb7, 0xa7, 0x03, 0xd5, 0xd3,
	0x56, 0x0f, 0x0d, 0xeb, 0x97, 0x0a, 0x18, 0x86, 0x61, 0x72, 0x98, 0x2a, 0x25, 0x23, 0x77, 0x73,
	0xd7, 0xd9, 0x6b, 0xfa, 0x05, 0xc6, 0x0a, 0x19, 0x26, 0xfd, 0x30, 0x1c, 0x46, 0x2e, 0xd1, 0x22,
	0x03, 0xb3, 0x55, 0xef, 0x45, 0x14, 0xf1, 0xd8, 0xdd, 0x32, 0xab, 0x32, 0x9c, 0xc9, 0x86, 0xd1,
	0x2b, 0xac, 0x46, 0x6a, 0x64, 0x19, 0xc6, 0x90, 0x0c, 0x93, 0x89, 0xce, 0x85, 0xa5, 0xfb, 0x58,
	0x0b, 0x4b, 0x02, 0x33, 0x47, 0x89, 0x05, 0x8f, 0x07, 0xba, 0x28, 0xb7, 0xb3, 0xcc, 0x29, 0x19,
	0xbb, 0x62, 0x9f, 0x54, 0x2b, 0xf6, 0x5f, 0x75, 0x68, 0xfa, 0x52, 0x2e, 0x74, 0x88, 0x76, 0x60,
	0x1d, 0x33, 0xa7, 0x68, 0x11, 0x39, 0xd2, 0x89, 0x77, 0x15, 0x0c, 0x4d, 0xcf, 0xc9, 0x00, 0x7d,
	0x69, 0xe5, 0x88, 0x5d, 0x32, 0xaf, 0x72, 0xb2, 0x9a, 0x32, 0x0b, 0x11, 0xf9, 0x4c, 0x24, 0x3c,
	0x4f, 0xde, 0x02, 0xa3, 0x6c, 0x19, 0x73, 0x3b, 0x7d, 0x0b, 0x8c, 0x32, 0x4c, 0xcb, 0x1b, 0x3e,
	0x9c, 0xe9, 0xcc, 0x6d, 0xf9, 0x05, 0x46, 0x67, 0x2f, 0x59, 0x74, 0xcd, 0xe3, 0x3c, 0x41, 0x73,
	0x84, 0x6b, 0x2e, 0x45, 0xa0, 0xaf, 0xcc, 0xa4, 0xa7, 0xc1, 0x7a, 0x2f, 0x99, 0x27, 0x40, 0x2b,
	0xdf, 0x2b, 0xc7, 0x18, 0x43, 0x91, 0x4c, 0xe6, 0xf2, 0x23, 0x66, 0xa1, 0x4e, 0xcb, 0x86, 0x6f,
	0x31, 0x98, 0x3f, 0x22, 0x79, 0xcd, 0x6e, 0x78, 0x3f, 0x0c, 0x45, 0xe4, 0xb6, 0xf5, 0x1d, 0xd8,
	0x14, 0x6a, 0x94, 0x8d, 0x25, 0x71, 0x3b, 0x3a, 0x71, 0x6d, 0xaa, 0x6c, 0x14, 0x3a, 0x71, 0xbb,
	0xbb, 0xf5, 0x95, 0x46, 0xa1, 0xd3, 0xd6, 0x52, 0xa1, 0xdf, 0x40, 0xab, 0x1f, 0x86, 0x99, 0xd0,
	0xed, 0xdd, 0xaf, 0x5f, 0x6a, 0x78, 0x2f, 0xa0, 0xf7, 0x63, 0x2a, 0xa6, 0xd7, 0x13, 0xc5, 0x62,
	0xdd, 0x45, 0xcb, 0xab, 0x73, 0xac, 0xab, 0xf3, 0xb6, 0x60, 0x73, 0x30, 0x67, 0x51, 0xc0, 0xcf,
	0xd9, 0x65, 0xc8, 0x75, 0xbb, 0xfd, 0x1e, 0x3a, 0x7f, 0x91, 0x22, 0xc2, 0x5c, 0xd0, 0xdd, 0xfb,
	0x25, 0x34, 0xe3, 0x3c, 0x2f, 0xf2, 0x8e, 0x96, 0xdd, 0xae, 0x49, 0x16, 0xbf, 0x10, 0x7b, 0xbf,
	0x87, 0xee, 0x71, 0xa4, 0x78, 0xfc, 0x90, 0xb5, 0x7d, 0xe8, 0x8d, 0xa4, 0x12, 0x53, 0x8e, 0x9b,
	0x57, 0xc7, 0x86, 0xb5, 0xfc, 0x73, 0x31, 0xf2, 0x36, 0xa1, 0x7b, 0xca, 0xd9, 0x0d, 0xd7, 0xdb,
	0xe3, 0x51, 0xfe, 0x6c, 0x13, 0x0f, 0x32, 0xd9, 0x85, 0xf6, 0x44, 0x28, 0xbc, 0x76, 0x6d, 0x50,
	0x94, 0xf0, 0x21, 0xe6, 0x2a, 0xf1, 0xa8, 0x7d, 0x3e, 0x1e, 0xb8, 0x73, 0x56, 0xd4, 0x7a, 0xe7,
	0x3f, 0x95, 0xf0, 0x41, 0x07, 0xf9, 0x2b, 0x90, 0x4c, 0x92, 0xf5, 0x7a, 0x9d, 0x12, 0xcf, 0xa0,
	0x75, 0xc9, 0x55, 0x7f, 0xa1, 0xdb, 0x81, 0x93, 0x0d, 0x8c, 0x82, 0xa0, 0x2f, 0x61, 0x3d, 0x9b,
	0x04, 0xda, 0xd3, 0x7b, 0x47, 0x45, 0xae, 0xe0, 0xfd, 0xdb, 0x59, 0xb1, 0x8e, 0x2e, 0xae, 0x7e,
	0x62, 0xdc, 0x3f, 0xea, 0x8a, 0x51, 0x56, 0xb7, 0x47, 0x99, 0x0b, 0x1b, 0xf9, 0x24, 0x31, 0x1f,
	0x16, 0x39, 0xfc, 0x7f, 0x4d, 0xa2, 0x28, 0xea, 0xf5, 0x95, 0xa2, 0xfe, 0x0d, 0x40, 0xe6, 0xac,
	0xee, 0xe9, 0x1b, 0x9f, 0x3a, 0x91, 0xa5, 0xe4, 0x0d, 0x60, 0xc7, 0x3e, 0x54, 0x56, 0x27, 0x5f,
	0x9a, 0xd6, 0xa7, 0xd0, 0xe9, 0xcf, 0x66, 0xda, 0x3f, 0x1d, 0x73, 0x6c, 0x64, 0x39, 0xce, 0x43,
	0x5e, 0x60, 0x6c, 0x1b, 0xc9, 0x6d, 0x72, 0x98, 0xde, 0x66, 0xe2, 0x2c, 0x4e, 0x36, 0xe5, 0xfd,
	0xdd, 0xb1, 0xcc, 0xa1, 0x27, 0x45, 0x50, 0x1d, 0x3b, 0xa8, 0xf6, 0x26, 0xb5, 0x95, 0x4d, 0xee,
	0x0f, 0x78, 0xe5, 0xdb, 0x61, 0x6d, 0xf5, 0xdb, 0x61, 0xc5, 0xb1, 0xc6, 0x5d, 0xc7, 0x7e, 0x00,
	0x6a, 0xba, 0xfd, 0xc3, 0xe2, 0xf4, 0x03, 0x50, 0x5f, 0x4f, 0x60, 0x34, 0x83, 0xcc, 0x97, 0x1a,
	0xf8, 0x06, 0xba, 0x3e, 0x67, 0xb3, 0x5b, 0xfc, 0x02, 0xd7, 0x6b, 0xf1, 0x48, 0x86, 0xc8, 0xc3,
	0x53, 0x12, 0xde, 0xaf, 0xa1, 0x37, 0xe1, 0x4a, 0x85, 0xbc, 0xd0, 0xd7, 0x5f, 0xf5, 0x86, 0xc9,
	0x17, 0x58, 0x8c, 0xf7, 0x47, 0x20, 0xe3, 0x34, 0x99, 0x63, 0xff, 0x2e, 0xd6, 0x7c, 0x81, 0x7f,
	0x2f, 0xa0, 0x87, 0x6c, 0x96, 0x67, 0x9f, 0xe9, 0xc8, 0x47, 0x15, 0x3d, 0x73, 0xc7, 0x77, 0xf4,
	0xf0, 0x78, 0xbe, 0x1e, 0xca, 0x23, 0xf9, 0x31, 0x1f, 0xc7, 0x25, 0xe1, 0x1d, 0x43, 0xf7, 0x78,
	0x21, 0x7f, 0x12, 0x83, 0x39, 0xcb, 0xda, 0xff, 0x8e, 0xae, 0x66, 0xfc, 0x9c, 0xcc, 0x4e, 0x96,
	0x23, 0x34, 0x13, 0x48, 0x16, 0x0e, 0xac, 0xca, 0x2c, 0x09, 0x8f, 0xd9, 0x66, 0xd0, 0x97, 0x4f,
	0x99, 0xc9, 0xe6, 0xb3, 0x6d, 0xa5, 0xc0, 0xd5, 0x2d, 0xea, 0xab, 0x5b, 0x6c, 0xc1, 0xe6, 0x58,
	0x8c, 0xb9, 0xc8, 0x4a, 0x0d, 0x37, 0xd9, 0xff, 0x6f, 0x03, 0x5a, 0x67, 0x3c, 0x49, 0x58, 0xc0,
	0x87, 0x47, 0xb4, 0x03, 0xcd, 0xb3, 0xc9, 0xab, 0x0b, 0x7c, 0x81, 0x91, 0x47, 0x05, 0x92, 0x51,
	0x40, 0x1c, 0xba, 0x05, 0x5d, 0x44, 0xc5, 0x6b, 0x8b, 0xd4, 0x0c, 0x55, 0x3c, 0x9d, 0x48, 0xbd,
	0x4a, 0xa1, 0xd6, 0x1a, 0xa5, 0xd0, 0xcb, 0xa9, 0xfc, 0x95, 0x41, 0x1a, 0x2b, 0x1c, 0xea, 0xad,
	0xd3, 0x1d, 0xa0, 0xc8, 0x55, 0x67, 0x29, 0xd9, 0xa0, 0x5f, 0xc1, 0x63, 0xe4, 0x57, 0x66, 0x27,
	0x69, 0xd2, 0x6d, 0x20, 0x28, 0xb0, 0x27, 0x28, 0x69, 0xd1, 0x27, 0xb0, 0xa5, 0xfd, 0xb4, 0x87,
	0x23, 0x01, 0x63, 0xbd, 0x3a, 0xf7, 0x48, 0xdb, 0xa8, 0x57, 0x86, 0x19, 0xe9, 0xdc, 0xa5, 0x51,
	0xbb, 0x4b, 0x1f, 0xc3, 0x26, 0xd2, 0xd6, 0x9c, 0x22, 0xbd, 0x55, 0x12, 0x35, 0x37, 0x0b, 0xb2,
	0x9c, 0x2b, 0x84, 0xac, 0x92, 0xa8, 0xb9, 0x45, 0x5d, 0xd8, 0xd6, 0x61, 0x5e, 0x19, 0x19, 0x84,
	0xde, 0x2b, 0xc1, 0x35, 0x8f, 0xe9, 0x73, 0x78, 0xba, 0x2a, 0x29, 0x7b, 0x01, 0xd9, 0x36, 0xa1,
	0xb1, 0xdb, 0x21, 0x79, 0x72, 0x87, 0x45, 0xdd, 0x1d, 0xfa, 0x14, 0x76, 0x90, 0xbd, 0xdb, 0x53,
	0xc8, 0x57, 0x46, 0x76, 0xb7, 0x5d, 0x10, 0xd7, 0x84, 0xa8, 0xd2, 0x09, 0xc8, 0xd7, 0x26, 0xd0,
	0xd5, 0x8a, 0x27, 0x4f, 0x8b, 0xc3, 0xac, 0xd4, 0x35, 0xf9, 0x99, 0x59, 0x51, 0x2d, 0x59, 0xf2,
	0xec, 0x1e, 0x1e, 0xf5, 0x7f, 0x5e, 0xdc, 0xb0, 0x5d, 0x74, 0xe4, 0xf9, 0x5d, 0x1a, 0xb5, 0x7f,
	0x61, 0xd2, 0x67, 0x25, 0xf1, 0xc9, 0xee, 0xfe, 0x7f, 0x1c, 0x68, 0x9a, 0x3f, 0x07, 0x68, 0x1b,
	0x36, 0x26, 0xef, 0x06, 0x83, 0xe3, 0xc9, 0x84, 0x3c, 0xc2, 0x6b, 0x7a, 0x97, 0xf0, 0xd8, 0xe7,
	0x4b, 0xce, 0x94, 0x4e, 0x65, 0xc2, 0x4b, 0x72, 0x21, 0x15, 0xcf, 0xc8, 0x2b, 0xdc, 0x53, 0x87,
	0x72, 0x18, 0x25, 0xe9, 0xd5, 0x95, 0x98, 0x0a, 0x1e, 0x29, 0x12, 0x60, 0xa0, 0x75, 0xc5, 0xf5,
	0x43, 0xdd, 0x05, 0x4f, 0xd2, 0x30, 0x24, 0x73, 0x3c, 0x0f, 0x5a, 0x18, 0x49, 0x65, 0xe5, 0x32,
	0x11, 0xe8, 0x21, 0xf2, 0x18, 0x91, 0xb7, 0xa9, 0x3a, 0x91, 0xa1, 0x7e, 0x73, 0x91, 0x9f, 0xcc,
	0x82, 0x3c, 0x5d, 0x72, 0x39, 0xb9, 0xc6, 0x50, 0x22, 0x9f, 0xbd, 0x52, 0x46, 0x52, 0xe5, 0x0a,
	0x24, 0xa4, 0x5f, 0xc3, 0x93, 0x52, 0x92, 0xd3, 0x68, 0x90, 0x2c, 0xf6, 0xff, 0xe1, 0x40, 0xd3,
	0xbc, 0xd4, 0xb0, 0xb4, 0x3f, 0x7c, 0xf8, 0x70, 0xa1, 0xf7, 0xd1, 0x85, 0xfe, 0x5a, 0x04, 0xfa,
	0x5a, 0x88, 0x83, 0xa1, 0x78, 0x1b, 0xf1, 0x31, 0x13, 0x31, 0xa9, 0xa1, 0xe8, 0xfc, 0xa3, 0x44,
	0x90, 0x90, 0x3a, 0xed, 0x42, 0xeb, 0x7c, 0x1e, 0x73, 0xfe, 0x46, 0x44, 0x33, 0xb2, 0x86, 0xc2,
	0x89, 0x8a, 0x99, 0x08, 0xe6, 0x8a, 0x34, 0x68, 0x0b, 0x1a, 0x27, 0x61, 0x9a, 0xcc, 0xc9, 0x3a,
	0xea, 0xe1, 0x99, 0x5f, 0xcb, 0x34, 0xe1, 0x64, 0x03, 0xf5, 0x4e, 0x64, 0x1a, 0xeb, 0x55, 0x4d,
	0x6c, 0x11, 0x66, 0x55, 0xa6, 0xdf, 0xa2, 0x3d, 0x00, 0x5f, 0xde, 0xb2, 0x30, 0xc3, 0xb0, 0xff,
	0x23, 0x34, 0x4d, 0x3a, 0xa2, 0x3b, 0xef, 0x99, 0x50, 0x59, 0x4b, 0x6a, 0xc3, 0xc6, 0x38, 0xe6,
	0x27, 0xa1, 0x5c, 0x12, 0x87, 0x36, 0x61, 0x4d, 0xff, 0xaa, 0xe1, 0xaf, 0xf3, 0x34, 0x8e, 0x48,
	0x1d, 0x9d, 0xf0, 0xc5, 0x0d, 0x8f, 0x73, 0xef, 0xf2, 0x77, 0x04, 0x69, 0xec, 0x8f, 0xa1, 0x63,
	0x7f, 0x7d, 0x68, 0xb3, 0xfd, 0xe1, 0xf9, 0x70, 0xf4, 0x8a, 0x3c, 0xd2, 0xab, 0xfa, 0xc3, 0xc9,
	0x71, 0x66, 0x74, 0xd0, 0x3f, 0x3d, 0x25, 0x35, 0x24, 0x07, 0xaf, 0x8f, 0x07, 0x6f, 0x48, 0x5d,
	0xef, 0xf4, 0xf6, 0xf4, 0x88, 0xac, 0x21, 0xd9, 0x3f, 0x3d, 0x1d, 0x8e, 0x48, 0x63, 0xff, 0x7b,
	0x68, 0x15, 0x6f, 0x54, 0xdc, 0x6c, 0x24, 0x2f, 0x34, 0x26, 0x8f, 0xe8, 0x26, 0xb4, 0x27, 0x0b,
	0x16, 0x86, 0x39, 0xe1, 0x60, 0x40, 0x0e, 0x45, 0x90, 0xc3, 0xda, 0xe5, 0xba, 0xfe, 0xc7, 0xeb,
	0xb7, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x97, 0xb9, 0x92, 0xfd, 0xfe, 0x12, 0x00, 0x00,
}
